# Generated by Django 5.2 on 2026-04-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_mysql_utf8mb4_blog_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='resume_html',
            field=models.TextField(blank=True, help_text='支持 HTML，与关于页相同；在模板中安全渲染', verbose_name='简历页内容'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='resume_tagline',
            field=models.CharField(blank=True, help_text='显示在横幅说明文字；留空可使用站点标语', max_length=200, verbose_name='简历页副标题'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='resume_title',
            field=models.CharField(blank=True, default='', help_text='留空则前台显示「个人简历」', max_length=100, verbose_name='简历页标题'),
        ),
    ]
